create database QLKHO;
use QLKHO;

drop table product;
drop table provider;
drop table users;
drop table ROLES;

CREATE TABLE PRODUCT(
	PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT,
	PRODUCT_NAME VARCHAR(30),
    PROVIDER_NAME VARCHAR(30),
    PRICE INT,
	AMOUNT INT(30),
    USER_ID VARCHAR(30),
    INPUT_DAY DATE,
    FOREIGN KEY (PROVIDER_NAME) REFERENCES PROVIDER(PROVIDER_NAME),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
    );


SELECT * FROM PRODUCT;
CREATE TABLE PROVIDER (
    PROVIDER_NAME VARCHAR(30) PRIMARY KEY,
    ADDRESS VARCHAR(30),
    PHONE_NUMBER CHAR(10) CHECK(REGEXP_REPLACE(PHONE_NUMBER,'[^0-9]', ''))
);
SELECT * FROM PROVIDER;
INSERT INTO PROVIDER VALUES('VINAMILK','Can Tho','0123456789');
INSERT INTO PROVIDER VALUES('KINH DO','Hà Nội','0375458318');
INSERT INTO PROVIDER VALUES('OSHI','Hồ Chí Minh','0123453420');
INSERT INTO PROVIDER VALUES('Chupa Chups','Hồ Chí Minh','0345236876');
INSERT INTO PROVIDER VALUES('Celano','Hà Nội','0123487690');
CREATE TABLE USERS(
	USER_ID VARCHAR(30)PRIMARY KEY,
    USER_NAME CHAR(30),
	USER_PASS VARCHAR(8),
    EMAIL VARCHAR(30) UNIQUE,
	GENDER CHAR(10),
    ROLE_ID VARCHAR(3),

    FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ROLE_ID)
);
SELECT * FROM USERS;

INSERT INTO USERS VALUES('1a','NHAN','11','NHAN@GMAIL.COM','F','001');
INSERT INTO USERS VALUES('2b','NHi','123','NHI@GMAIL.COM','F','003');
INSERT INTO USERS VALUES('3c','THAI','110','THAI@GMAIL.COM','M','002');

update users set gender='Male' where user_id='3c';
delete from users where user_id='12a';
CREATE TABLE ROLES(
	ROLE_ID VARCHAR(3) PRIMARY KEY,
	ROLE_NAME CHAR(30)
);

INSERT INTO ROLES VALUES('001','QUAN LI');
INSERT INTO ROLES VALUES('002',' PHO QUAN LI');
INSERT INTO ROLES VALUES('003','NHAN VIEN');
SELECT* FROM ROLES;
#PROCEDURE
#=========================================INSERT_PRODUCT======================================
DELIMITER $$
CREATE PROCEDURE INSERT_PRODUCT(PNAME VARCHAR(30),PROVIDERNAME VARCHAR(30),PRICE VARCHAR(30),PAMOUNT INT,USERID VARCHAR(30),INPUTDAY DATE)
BEGIN
	INSERT INTO PRODUCT(PRODUCT_NAME,PROVIDER_NAME,PRICE,AMOUNT,USER_ID,INPUT_DAY)VALUES(PNAME,PROVIDERNAME,PRICE,PAMOUNT,USERID,INPUTDAY);
END$$
DROP PROCEDURE INSERT_PRODUCT$$
CALL INSERT_PRODUCT('RICE','VINAMILK','200','20','1a','2023-12-24')$$
#==========================================DELETE=======================================
CREATE PROCEDURE DEL_PRODUCT( ID INT)
BEGIN
	IF EXISTS (SELECT * FROM PRODUCT WHERE PRODUCT_ID=ID)
    then
		DELETE FROM PRODUCT WHERE PRODUCT_ID=ID;
	END IF;
END$$

#=================================================UPDATE======================================

CREATE PROCEDURE UPDATE_PRODUCT(ID INT,PNAME VARCHAR(30),PROVIDENAME VARCHAR(30),COST INT,PAMOUNT INT,USERID VARCHAR(30),DATEADD DATE)
BEGIN
		UPDATE PRODUCT SET PRODUCT_NAME=PNAME, PROVIDER_NAME=PROVIDENAME, PRICE=COST, AMOUNT=PAMOUNT, USER_ID=USERID, INPUT_DAY=DATEADD WHERE PRODUCT_ID=ID;
END$$
DROP PROCEDURE UPDATE_PRODUCT$$
SELECT * FROM PRODUCT$$
Call UPDATE_PRODUCT('2','RICES','VINAMILK',200,20,'4d','2023-12-24')$$
desc product$$
#================================================SEARCH========================================

CREATE PROCEDURE SEARCH_PRODUCT(ID INT)
BEGIN
	IF EXISTS (SELECT * FROM PRODUCT WHERE PRODUCT_ID=ID)
    THEN
	SELECT PRODUCT_NAME,PROVIDER_NAME,PRICE,AMOUNT,USER_ID, INPUT_DAY FROM PRODUCT WHERE PRODUCT_ID = ID;
    END IF;
END$$
CALL SEARCH_PRODUCT(3)$$
DROP procedure SEARCH_PRODUCT$$
#============================================LOGIN=====================================
CREATE PROCEDURE LOGIN_USER (ID VARCHAR(30), PASS VARCHAR(30))
BEGIN
	SELECT * FROM USERS WHERE USER_ID=ID AND USER_PASS=PASS;
END$$
CALL LOGIN_USER('3c','110')$$
#==========================================SIGNUP===================================
CREATE PROCEDURE INSERT_USER(UID VARCHAR(30),UNAME CHAR(30),UPASS VARCHAR(30),UEMAIL VARCHAR(30),UGENDER CHAR(10),UROLE VARCHAR(3))
BEGIN
	INSERT INTO USERS(USER_ID,USER_NAME,USER_PASS,EMAIL,GENDER,ROLE_ID) VALUES(UID,UNAME,UPASS,UEMAIL,UGENDER,UROLE);
END$$

DROP PROCEDURE INSERT_USER$$
CALL INSERT_USER('6d','NHAN','290','nhan295@gmail.com','Female','003')$$
SELECT * FROM USERS$$

#=============================================SUM PRODUCT========================
CREATE FUNCTION SUM_PRODUCT()
	RETURNS INT
BEGIN
	RETURN(SELECT SUM(AMOUNT) FROM PRODUCT);
END$$
DROP FUNCTION SUM_PRODUCT$$
SELECT SUM_PRODUCT()$$